/* Schema creation */

CREATE TABLE LISTE_IDEE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(255)
);

CREATE TABLE IDEE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITRE VARCHAR(255),
    CONTENU VARCHAR(255),
    AUTEUR VARCHAR(255),
    LISTE_IDEE_ID BIGINT
);

CREATE TABLE BOITEAIDEE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(255),
    LISTE_IDEE_ID BIGINT
);

ALTER TABLE BOITEAIDEE ADD FOREIGN KEY (LISTE_IDEE_ID) REFERENCES LISTE_IDEE(ID);
ALTER TABLE IDEE ADD FOREIGN KEY (LISTE_IDEE_ID) REFERENCES LISTE_IDEE(ID);

/* Data insertion */

INSERT INTO LISTE_IDEE(ID, NOM) VALUES(1, 'liste');
INSERT INTO BOITEAIDEE(ID, NOM, LISTE_IDEE_ID) VALUES(1, 'BAI', 1);

/* test liste 
INSERT INTO IDEE(ID, TITRE, CONTENU, AUTEUR, LISTE_IDEE_ID) VALUES(1, 'idee1', 'contenu1', 'auteur1', 1);
INSERT INTO IDEE(ID, TITRE, CONTENU, AUTEUR, LISTE_IDEE_ID) VALUES(2, 'idee2', 'contenu2', 'auteur2', 1);
INSERT INTO IDEE(ID, TITRE, CONTENU, AUTEUR, LISTE_IDEE_ID) VALUES(3, 'idee3', 'contenu3', 'auteur3', 1);
 fin test liste */