/* Schema creation */

CREATE TABLE CARTE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DATE_MODIF VARCHAR(255),
    NOM VARCHAR(255)
);

CREATE TABLE INGREDIENT(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(255),
    LIBELLE VARCHAR(255),
    QUANTITE INTEGER,
    PIZZA_ID BIGINT
);

CREATE TABLE MAGASIN(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(255),
    SIRET VARCHAR(255),
    SLOGAN VARCHAR(255),
    CARTE_ID BIGINT,
    STOCK_ID BIGINT
);

CREATE TABLE PIZZA(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    NOM VARCHAR(255),
    CARTE_ID BIGINT
);

CREATE TABLE QUANTITE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(255),
    VALEUR INTEGER,
    STOCK_ID BIGINT
);

CREATE TABLE STOCK(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(255)
);


ALTER TABLE MAGASIN ADD FOREIGN KEY (CARTE_ID) REFERENCES CARTE(ID);
ALTER TABLE MAGASIN ADD FOREIGN KEY (STOCK_ID) REFERENCES STOCK(ID);
ALTER TABLE PIZZA ADD FOREIGN KEY (CARTE_ID) REFERENCES CARTE(ID);
ALTER TABLE INGREDIENT ADD FOREIGN KEY (PIZZA_ID) REFERENCES PIZZA(ID);
ALTER TABLE QUANTITE ADD FOREIGN KEY (STOCK_ID) REFERENCES STOCK(ID);

/* Data insertion */

INSERT INTO CARTE(ID, DATE_MODIF, NOM) VALUES(10, '2017-01-03', 'Principale');

INSERT INTO STOCK(ID, NOM) VALUES(1, 'Principal');

INSERT INTO QUANTITE(ID, CODE, VALEUR, STOCK_ID) VALUES(1, 'tomate', 10000, 1);
INSERT INTO QUANTITE(ID, CODE, VALEUR, STOCK_ID) VALUES(2, 'mozarella', 20000, 1);
INSERT INTO QUANTITE(ID, CODE, VALEUR, STOCK_ID) VALUES(3, 'basilic', 1000, 1);

INSERT INTO MAGASIN(ID, NOM, SIRET, SLOGAN, CARTE_ID, STOCK_ID)
    VALUES(1, 'Pizzaiole', '123456789123', 'Des pizzas par des artistes, pour des gourmands !', 10, 1);

INSERT INTO PIZZA(ID, CODE, DESCRIPTION, NOM, CARTE_ID)
    VALUES(1, 'margarita', STRINGDECODE('Concass\u00e9 de tomates, mozzarella, feuilles de basilic frais'), 'Margarita', 10);
INSERT INTO PIZZA(ID, CODE, DESCRIPTION, NOM, CARTE_ID)
    VALUES(2, 'napoletana', STRINGDECODE('Sauce tomate, mozzarella, anchois, c\u00e2pres \u00e0 queue (caprons)'), 'Napoletana', 10);

INSERT INTO INGREDIENT(ID, CODE, LIBELLE, QUANTITE, PIZZA_ID) VALUES(1, 'tomate', 'Tomate', 100, 1);
INSERT INTO INGREDIENT(ID, CODE, LIBELLE, QUANTITE, PIZZA_ID) VALUES(2, 'mozarella', 'Mozarella', 100, 1);
INSERT INTO INGREDIENT(ID, CODE, LIBELLE, QUANTITE, PIZZA_ID) VALUES(3, 'basilic', 'Basilic', 10, 1);
INSERT INTO INGREDIENT(ID, CODE, LIBELLE, QUANTITE, PIZZA_ID) VALUES(4, 'tomate', 'Tomate', 100, 2);
INSERT INTO INGREDIENT(ID, CODE, LIBELLE, QUANTITE, PIZZA_ID) VALUES(5, 'mozarella', 'Mozarella', 100, 2);
INSERT INTO INGREDIENT(ID, CODE, LIBELLE, QUANTITE, PIZZA_ID) VALUES(6, 'anchois', 'Anchois', 80, 2);
INSERT INTO INGREDIENT(ID, CODE, LIBELLE, QUANTITE, PIZZA_ID) VALUES(7, 'capre', 'Capre', 800, 2);
