/* Schema creation */

CREATE TABLE BOITEAIDEE(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOM VARCHAR(255)
);CREATE TABLE TEST(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY
);



/* Data insertion */

INSERT INTO BOITEAIDEE(ID, NOM) VALUES(1, 'BAI');
